package com.android.startupwizard

fun getDisplayName(localName: String): String {
    return when (localName) {
        "ca-ES" -> "Català (Espanya)"
        "cs-CZ" -> "Čeština (Česko)"
        "da-DK" -> "Dansk (Danmark)"
        "de-DE" -> "Deutsch (Deutschland)"
        "de-AT" -> "Deutsch (Österreich)"
        "et-EE" -> "Eesti (Eesti)"
        "en-GB" -> "English (United Kingdom)"
        "en-US" -> "English (United States)"
        "es-ES" -> "Español (España)"
        "es-US" -> "Español (Estados Unidos)"
        "fi_PH" -> "Filipino (Pilipinas)"
        "fr-FR" -> "Français (France)"
        "hr-HR" -> "Hrvatski (Hrvatska)"
        "id-ID" -> "Indonesia (Indonesia)"
        "it-IT" -> "Italiano (Italia)"
        "lv-LV" -> "Latviešu (Latvija)"
        "lt-LT" -> "Lietuvių (Lietuva)"
        "hu-HU" -> "Magyar (Magyarország)"
        "ms-MY" -> "Melayu (Malaysia)"
        "nl-NL" -> "Nederlands (Nederland)"
        "nb-NO" -> "Norsk bokmål (Norge)"
        "pl-PL" -> "Polski (Polska)"
        "pt-BR" -> "Português (Brasil)"
        "pt-PT" -> "Português (Portugal)"
        "ro-RO" -> "Română (România)"
        "sk-SK" -> "Slovenčina (Slovensko)"
        "sl-SI" -> "Slovenščina (Slovenija)"
        "fi-FI" -> "Suomi (Suomi)"
        "sv-SE" -> "Svenska (Sverige)"
        "vi-VN" -> "Tiếng Việt (Việt Nam)"
        "tr-TR" -> "Türkçe (Türkiye)"
        "el-GR" -> "Ελληνικά (Ελλάδα)"
        "bg-BG" -> "Български (България)"
        "ru-RU" -> "Pусский (Россия)"
        "sr-RS" -> "Cрпски (Србија)"
        "uk-UA" -> "Українська (Україна)"
        "hy-AM" -> "հայերեն (Հայաստան)"
        "he-IL" -> "עברית (ישראל)"
        "ar-EG" -> "العربية (مصر)"
        "fa-IR" -> "فارسی (ایران)"
        "hi-IN" -> "हिन्दी (भारत)"
        "th-TH" -> "ไทย (ไทย)"
        "my-MM" -> "ြန်မာ (မြန်မာ)"
        "km-KH" -> "ខ្មែរ (កម្ពុជា)"
        "ko-KR" -> "한국어 (대한민국)"
        "zh-CN" -> "中文 (简体)"
        "zh-TW" -> "中文 (繁體)"
        "zh-HK" -> "中文 (香港)"
        "ja-JP" -> "日本語 (日本)"
        else -> "中文 (简体)"
    }
}